In [19]:
import tensorflow as tf
import numpy as np

#load training data to array
# unpack=True 和文件中的相反即转置
xy = np.loadtxt('train.txt', unpack=True, dtype='float32')
print (xy )
print ('-----------------------------------------')
# x is training data & y is result(binary classification)
#[0:-1] 不取最后一行 [0:]取最后一行
x = xy[0:-1]
y = xy[-1]
print (x )
print ('-----------------------------------------')
print (y )
# process placeholder
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

# define W, h and hypothesis(Logistic Classification)
# sigmoid hypothesis = 1/1+e^h
W = tf.Variable(tf.random_uniform([1, len(x)], -1.0, 1.0))
print(W.shape)
# this is W*X
h = tf.matmul(W, X)
hypothesis = tf.div(1., 1.+tf.exp(-h))

# cost function(logistic, can get global minimum using GradientDescent algorithm)
cost = -tf.reduce_mean(Y*tf.log(1+hypothesis)+(1-Y)*tf.log(1-hypothesis))

# minimizing cost function(cause' convex function)
a = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(a)
trained_data = optimizer.minimize(cost)

init = tf.global_variables_initializer()
session = tf.Session()
session.run(init)

# training matrix w
for step in range(1001):
    session.run(trained_data, feed_dict={X:x, Y:y})
    if step%100 == 0:
        print (step, session.run(cost, feed_dict={X:x, Y:y}), session.run(W))


# examine classification attention iuput x only three ，not six
print ('-----------------------------------------')
print (session.run(hypothesis, feed_dict={X:[[1], [2], [2]]}) > 0.5)
print (session.run(hypothesis, feed_dict={X:[[1], [3], [4]]}) > 0.5)
print (session.run(hypothesis, feed_dict={X:[[1], [4], [4]]}) > 0.5)
print (session.run(hypothesis, feed_dict={X:[[1], [4], [5]]}) > 0.5)
print (session.run(hypothesis, feed_dict={X:[[1], [5], [4]]}) > 0.5)
print (session.run(hypothesis, feed_dict={X:[[1], [5], [5]]}) > 0.5)
print (session.run(hypothesis, feed_dict={X:[[1], [7], [7]]}) > 0.5)




[[ 1.  1.  1.  1.  1.  1.]
 [ 2.  3.  3.  5.  7.  2.]
 [ 1.  2.  4.  5.  5.  5.]
 [ 0.  0.  0.  1.  1.  1.]]
-----------------------------------------
[[ 1.  1.  1.  1.  1.  1.]
 [ 2.  3.  3.  5.  7.  2.]
 [ 1.  2.  4.  5.  5.  5.]]
-----------------------------------------
[ 0.  0.  0.  1.  1.  1.]
(1, 3)
0 0.403011 [[ 0.21238066 -0.28021052  0.70771551]]
100 -0.0224175 [[-0.22211769 -1.30895209  0.55490321]]
200 -0.0504703 [[-0.32861289 -1.71382904  0.87553763]]
300 -0.065772 [[-0.39772567 -2.0311501   1.09192598]]
400 -0.0752383 [[-0.44529817 -2.28593898  1.25691652]]
500 -0.0816623 [[-0.48041162 -2.49814773  1.39057922]]
600 -0.0863092 [[-0.50771552 -2.67987108  1.50304353]]
700 -0.0898285 [[-0.52978182 -2.83875823  1.60017669]]
800 -0.0925874 [[-0.54814523 -2.97991157  1.685691  ]]
900 -0.0948089 [[-0.56377798 -3.10690188  1.76208901]]
1000 -0.0966367 [[-0.57732975 -3.22231793  1.8311398 ]]
-----------------------------------------
[[False]]
[[False]]
[[False]]
[[False]]
[[False]]