In [6]:
import tensorflow as tf
import numpy as np

# numpy !
xy = np.loadtxt('softmax_classification.txt', unpack=True, dtype='float32')
print(xy)
print("_______________________________")
# transpose matrix
x_data = np.transpose(xy[0:3])
y_data = np.transpose(xy[3:])
print(x_data)
print("_______________________________")
print(y_data)
# placeholder
X = tf.placeholder(tf.float32, [None, 3])
Y = tf.placeholder(tf.float32, [None, 3])

# initialize matrix
W = tf.Variable(tf.zeros([3, 3]))

# get hypothesis softmax
hypothesis = tf.nn.softmax(tf.matmul(X, W))

# get cost function D(S,L) --> softmax algorithm(multinomial classification)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), reduction_indices=1))

# gradientDescent algorithm
optimizer = tf.train.GradientDescentOptimizer(0.001).minimize(cost)
init = tf.global_variables_initializer()

# define session, train
with tf.Session() as session:
    session.run(init)

    for step in range(2001):
        session.run(optimizer, feed_dict={X:x_data, Y:y_data})
        if step % 200 == 0:
            print (step, session.run(cost, feed_dict={X:x_data, Y:y_data}), session.run(W))


    # it can be not accurate because training data has only 9 samples!
    a = session.run(hypothesis, feed_dict={X:[[1, 11, 7]]})
    print (a, session.run(tf.argmax(a, 1)))

    b = session.run(hypothesis, feed_dict={X: [[1, 0, 1]]})
    print (b, session.run(tf.argmax(b, 1)))


[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 2.  3.  3.  5.  4.  2.  8.  7.  9.]
 [ 1.  2.  4.  5.  5.  5.  8.  9.  6.]
 [ 0.  0.  0.  0.  0.  0.  1.  1.  1.]
 [ 0.  0.  0.  1.  1.  1.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.  0.  0.  0.  0.]]
_______________________________
[[ 1.  2.  1.]
 [ 1.  3.  2.]
 [ 1.  3.  4.]
 [ 1.  5.  5.]
 [ 1.  4.  5.]
 [ 1.  2.  5.]
 [ 1.  8.  8.]
 [ 1.  7.  9.]
 [ 1.  9.  6.]]
_______________________________
[[ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]]
0 1.09528 [[ -2.98023238e-11  -2.23517420e-11  -3.72529056e-11]
 [  1.07407407e-03  -3.70370428e-04  -7.03703903e-04]
 [  8.88888899e-04  -2.98023238e-11  -8.88889132e-04]]
200 0.988634 [[-0.02455868  0.00525795  0.01930073]
 [ 0.0688806  -0.03887193 -0.03000867]
 [ 0.02965615  0.03294891 -0.06260502]]
400 0.963697 [[-0.05602691  0.0105421   0.04548484]
 [ 0.09099286 -0.0708542  -0.02013875]
 [ 0.01627473  0.06602915 -0.08230